name: CI Build, Test, and Dependency Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install OWASP Dependency-Check
      run: |
        curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip
        unzip dependency-check-8.3.1-release.zip -d dependency-check

    - name: Run Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh --project MyApp --scan ./ --format ALL --out ./dependency-check-report

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report
