name: SonarCloud Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sonarcloud:
    runs-on: windows-latest  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Install SonarScanner Global Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Run Tests and Collect Code Coverage
      run: |
        vsts-ci.yml

    - name: Run SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet sonarscanner begin /k:"drm0011_BookClubApp" /o:"drm0011" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
        dotnet build
        dotnet test --logger:trx --results-directory ./TestResults
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
